# Taps
tap 'caskroom/cask'
tap 'caskroom/fonts'
tap 'caskroom/versions'
tap 'caskroom/drivers'
tap 'homebrew/php'

# Install ZSH
brew 'zsh'
brew 'zsh-autosuggestions'
brew 'zsh-completions'
brew 'zsh-syntax-highlighting'

# Install GNU core utilities (those that come with macOS are outdated)
brew 'coreutils'

# Install GNU `find`, `locate`, `updatedb`, and `xargs`, g-prefixed
brew 'findutils'

# Install Bash 4
brew 'bash'

# Install more recent versions of some macOS tools
brew 'grep'

# Install Binaries
brew 'composer'
brew 'diff-so-fancy'
brew 'exa'
brew 'git'
brew 'httpie'
brew 'hub'
brew 'mackup'
brew 'mas'
brew 'nano'
brew 'node'
brew 'ssh-copy-id'
brew 'tidy-html5'
brew 'trash'
brew 'tree'
brew 'unar'
brew 'wget'
brew 'wifi-password'
brew 'yarn'

# Development
brew 'php71'
brew 'mariadb'
brew 'wp-cli'
brew 'pre-commit'

# Apps
cask 'alfred'
cask 'appcleaner'
cask 'bartender'
cask 'beardedspice'
cask 'betterzip'
cask 'caffeine'
cask 'cheatsheet'
cask 'cyberduck'
cask 'dash'
cask 'dropbox'
cask 'endurance'
cask 'eve'
cask 'fantastical'
cask 'firefox'
cask 'flash-player'
cask 'flux'
cask 'gitkraken'
cask 'google-chrome'
cask 'hammerspoon'
cask 'insomnia'
cask 'iterm2'
cask 'jadengeller-helium'
cask 'kaleidoscope'
cask 'karabiner-elements'
cask 'logitech-gaming-software'
cask 'logitech-options'
cask 'logitech-unifying'
cask 'macdown'
cask 'mysqlworkbench'
cask 'now'
cask 'phpstorm'
cask 'screenflow'
cask 'sequel-pro'
cask 'shuttle'
cask 'silverlight'
cask 'sketch'
cask 'skitch'
cask 'slack'
cask 'spectacle'
cask 'spotify'
cask 'sublime-text'
cask 'the-unarchiver'
cask 'transmission'
cask 'transmit'
cask 'vagrant'
cask 'virtualbox'
cask 'visual-studio-code'
cask 'vlc'
cask 'zoomus'

# Quicklook
cask 'qlcolorcode'
cask 'qlmarkdown'
cask 'qlstephen'
cask 'qlvideo'
cask 'qqlimagesize'
cask 'quicklook-json'
cask 'suspicious-package'
cask 'webpquicklook'

# Fonts
cask 'font-droidsansmono-nerd-font-mono'
cask 'font-fira-code'
cask 'font-fira-mono'
cask 'font-fira-sans'
cask 'font-firacode-nerd-font-mono'
cask 'font-firamono-nerd-font-mono'
cask 'font-hack'
cask 'font-hack-nerd-font'
cask 'font-hack-nerd-font-mono'
cask 'font-inconsolata-g-for-powerline'
cask 'font-input'
cask 'font-lato'
cask 'font-lora'
cask 'font-merriweather'
cask 'font-monserrat'
cask 'font-noto-sans'
cask 'font-noto-sans-mono'
cask 'font-office-code-pro'
cask 'font-open-sans'
cask 'font-open-sans-condensed'
cask 'font-pt-sans'
cask 'font-raleway'
cask 'font-roboto'
cask 'font-roboto-condensed'
cask 'font-roboto-mono-nerd-font-mono'
cask 'font-roboto-slab'
cask 'font-source-code-pro'
cask 'font-source-code-pro-for-powerline'
cask 'font-source-sans-pro'
cask 'font-source-serif-pro'
cask 'font-ubuntu-nerd-font'
cask 'font-ubuntu-nerd-font-mono'
cask 'font-ubuntumono-nerd-font'
cask 'font-ubuntumono-nerd-font-mono'

# Install Mac App Store apps
mas '1Password', id: 443987910
mas 'Giphy Capture', id: 668208984
mas 'Spark', id: 1176895641
mas 'Yoink', id: 457622435
