#!/usr/bin/env zsh

PATH=$PATH:/usr/local/bin

alias_file="$HOME/.dotfiles/system/brew-php-aliases.zsh"

printf "#!/usr/bin/env zsh \n" > $alias_file

declare -A brewPhpInstallations
brewPhpInstallations=($(brew ls --versions | ggrep -Po 'php\S*\b\s\d\.\d' | uniq | sort))
# jq filter: brew info --json --installed | jq '.[] | select(.name|startswith("php")) | .name + " " + .installed[].version | match("(php\\S*)\\b\\s(\\d\\.\\d)").captures | map(.string)' will return an array like
# [
#   "php",
#   "8.1"
# ]
# [
#   "php@7.3",
#   "7.3"
# ]
# [
#   "php@7.4",
#   "7.4"
# ]

for brewName version in ${(kv)brewPhpInstallations}; do

    value="{"

    for otherPhpInstalls in ${(k)brewPhpInstallations}; do
        if [ "${otherPhpInstalls}" != "${brewName}" ]; then
            value="${value} brew unlink ${otherPhpInstalls};"
        fi
    done

    value="${value} brew link ${brewName} --force --overwrite; } &> /dev/null && php -v"

    printf alias \'${version}\'=\'${value}\' >> $alias_file
done
